# Generated by Django 4.1.13 on 2024-06-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mistral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
    ]
